spring:
  application:
    name: spring-cloud-ribbon

server:
  port: 8888
  contextPath: /data-access-service


webank:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:25000,http://localhost:25010
    ServerListRefreshInterval: 15000